### ISSUE TITLE
Have native support for DAILA in BinSync

### ISSUE THREAD

**Issue by mahaloz** [binsync/binsync#262]
## Tasks
- [ ] Refactor DAILA (https://github.com/mahaloz/DAILA) to only use the BinSync API for getting function information
- [ ] Transition DAILA into a library usable format so that we can call it from BinSync
- [ ] Add code in BinSync to do something like the following
```python
from daila import chatgpt_rename_function
for function in controller.functions:
    dec = controller.decompile(function)
    func_name = chatgpt_rename_function(dec)
    function.name  = func_name 
    # saves it to a project that should be a duplicate with a new user
    controller.push_artifact(function)
```
- [ ] Make cmdline access from `binsync` so you can start it from there!
