### ISSUE TITLE
Add headless support for `IDABSController`

### ISSUE THREAD

**Issue by mahaloz** [binsync/binsync#268]
### Description

Since #265, the angr decompiler has been supported for headless use in scripts, i.e., you can start a BSController in a script not running in a decompiler and it will start that decompiler to run itself in. 

This can be see here, which uses the `headless=True` kwarg to get a angr controller:
https://github.com/binsync/binsync/blob/aaa2af05ea1fc567792d283c73dfe685e0c7bbc0/binsync/extras/ai/openai_bs_user.py#L60

We need this support in IDA.

## Tasks
To do this, only a few things need to be done:
- [ ] Add a way to find the `idat64` binary, so we can start scripts using that path
- [ ] Test stdout handling with `idat64`
- [ ] Add checks throughout the IDABSController to check for headless when getting an instance to decompilation
- [ ] Make a way to switch between `idaapi.decompile` and getting a GUI pointer in the `compat.py` usage (will require replacements across the file).
