### ISSUE TITLE
Major Refactor: Port interface backend to LibBS

### ISSUE THREAD

**Issue by mahaloz** [binsync/binsync#345]
## Background
A majority of the code inside the BinSync code base is code for abstracting access to decompiler APIs. Although BinSync is largely based on its ability to abstract away interactions between decompilers, it's not for abstracting the API. In response, the BinSync team has largely pushed for a new library called [LibBS](https://github.com/binsync/libbs), which will abstract away artifacts, API calls, and common GUI among the many decompilers. 

Ideally, in this refactor we remove the majority of all decompiler-specific code, leaving only two types of code in this repo:
1. GUI code for the specific BinSync interfaces
2. Version control code for interacting with Git

Realistically, there will be a small amount of decompiler-specific code for fixing quirks across decompilers for some use cases. 

## TODO
- [x] Remove the abstracted PyQT Gui code folder
- [x] Remove the installer
- [x] Remove all decompiler specific code, aside from GUIs
- [ ] Finish implementing callback handlers for Binja (https://github.com/binsync/libbs/issues/17)
- [ ] Test all decompilers
    - [ ] IDA Pro
    - [ ] Binja
    - [ ] Ghidra
    - [ ] angr

### Additional context

The majority of this work will be done by @mahaloz and @Flipout50. Msg @mahaloz on Discord if you would like to help.
